/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated.crm'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated.crm.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedCrmTasksRouteImport } from './routes/_authenticated.crm.tasks'
import { Route as AuthenticatedCrmSettingsRouteImport } from './routes/_authenticated.crm.settings'
import { Route as AuthenticatedCrmMapRouteImport } from './routes/_authenticated.crm.map'
import { Route as AuthenticatedCrmContingentsRouteImport } from './routes/_authenticated.crm.contingents'
import { Route as AuthenticatedCrmCommissionsRouteImport } from './routes/_authenticated.crm.commissions'
import { Route as AuthenticatedCrmCampaignsRouteImport } from './routes/_authenticated.crm.campaigns'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminMessagingRouteImport } from './routes/_authenticated.admin.messaging'
import { Route as AuthenticatedAdminMarketsRouteImport } from './routes/_authenticated.admin.markets'
import { Route as AuthenticatedAdminKnowledgeRouteImport } from './routes/_authenticated.admin.knowledge'
import { Route as AuthenticatedAdminDevicesRouteImport } from './routes/_authenticated.admin.devices'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated.admin.commissions'
import { Route as AuthenticatedCrmTeamIndexRouteImport } from './routes/_authenticated.crm.team.index'
import { Route as AuthenticatedCrmLeadsIndexRouteImport } from './routes/_authenticated.crm.leads.index'
import { Route as AuthenticatedAdminKnowledgeIndexRouteImport } from './routes/_authenticated.admin.knowledge.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicTwilioVoiceAppRouteImport } from './routes/api/public/twilio/voice-app'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio/voice'
import { Route as ApiPublicTwilioSmsStatusRouteImport } from './routes/api/public/twilio/sms-status'
import { Route as ApiPublicTwilioSmsRouteImport } from './routes/api/public/twilio/sms'
import { Route as ApiPublicTwilioRecordingRouteImport } from './routes/api/public/twilio/recording'
import { Route as ApiPublicTwilioCallStatusRouteImport } from './routes/api/public/twilio/call-status'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicNectarpayWebhookRouteImport } from './routes/api/public/nectarpay/webhook'
import { Route as ApiPublicLeadsIntakeRouteImport } from './routes/api/public/leads/intake'
import { Route as ApiPublicEUnsubscribeRouteImport } from './routes/api/public/e/unsubscribe'
import { Route as ApiPublicEOpenRouteImport } from './routes/api/public/e/open'
import { Route as ApiPublicEClickRouteImport } from './routes/api/public/e/click'
import { Route as ApiPublicDocsTokenRouteImport } from './routes/api/public/docs/$token'
import { Route as ApiPublicCronContingentsRouteImport } from './routes/api/public/cron/contingents'
import { Route as ApiPublicAuthWalletStatusRouteImport } from './routes/api/public/auth/wallet-status'
import { Route as ApiPublicAuthWalletExchangeRouteImport } from './routes/api/public/auth/wallet-exchange'
import { Route as ApiPublicAuthWalletChallengeRouteImport } from './routes/api/public/auth/wallet-challenge'
import { Route as ApiPublicAuthWalletCallbackRouteImport } from './routes/api/public/auth/wallet-callback'
import { Route as AuthenticatedCrmTeamRepIdRouteImport } from './routes/_authenticated.crm.team.$repId'
import { Route as AuthenticatedCrmLeadsIdRouteImport } from './routes/_authenticated.crm.leads.$id'
import { Route as AuthenticatedAdminKnowledgeTermsRouteImport } from './routes/_authenticated.admin.knowledge.terms'
import { Route as AuthenticatedAdminKnowledgePrivacyRouteImport } from './routes/_authenticated.admin.knowledge.privacy'
import { Route as AuthenticatedAdminKnowledgeNewRouteImport } from './routes/_authenticated.admin.knowledge.new'
import { Route as AuthenticatedAdminKnowledgeMembersHeatmapRouteImport } from './routes/_authenticated.admin.knowledge.members-heatmap'
import { Route as AuthenticatedAdminKnowledgeManifestoRouteImport } from './routes/_authenticated.admin.knowledge.manifesto'
import { Route as AuthenticatedAdminKnowledgeExecutiveSummaryRouteImport } from './routes/_authenticated.admin.knowledge.executive-summary'
import { Route as AuthenticatedAdminKnowledgeConvenienceDoctrineRouteImport } from './routes/_authenticated.admin.knowledge.convenience-doctrine'
import { Route as AuthenticatedAdminKnowledgeTrainingSalesRepsRouteImport } from './routes/_authenticated.admin.knowledge.training.sales-reps'
import { Route as AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRouteImport } from './routes/_authenticated.admin.knowledge.training.merchant-onboarding'
import { Route as AuthenticatedAdminKnowledgeTrainingCryptopopRouteImport } from './routes/_authenticated.admin.knowledge.training.cryptopop'
import { Route as AuthenticatedAdminKnowledgePitchNewMarketsRouteImport } from './routes/_authenticated.admin.knowledge.pitch.new-markets'
import { Route as AuthenticatedAdminKnowledgePitchMerchantsRouteImport } from './routes/_authenticated.admin.knowledge.pitch.merchants'
import { Route as AuthenticatedAdminKnowledgePitchConsumersRouteImport } from './routes/_authenticated.admin.knowledge.pitch.consumers'
import { Route as AuthenticatedAdminKnowledgeItemItemIdRouteImport } from './routes/_authenticated.admin.knowledge.item.$itemId'
import { Route as ApiPublicDocsTokenFileIdRouteImport } from './routes/api/public/docs/$token.file.$id'
import { Route as AuthenticatedAdminKnowledgeItemItemIdEditRouteImport } from './routes/_authenticated.admin.knowledge.item.$itemId.edit'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedCrmTasksRoute = AuthenticatedCrmTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmSettingsRoute =
  AuthenticatedCrmSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmMapRoute = AuthenticatedCrmMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmContingentsRoute =
  AuthenticatedCrmContingentsRouteImport.update({
    id: '/contingents',
    path: '/contingents',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCommissionsRoute =
  AuthenticatedCrmCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCampaignsRoute =
  AuthenticatedCrmCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagingRoute =
  AuthenticatedAdminMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketsRoute =
  AuthenticatedAdminMarketsRouteImport.update({
    id: '/markets',
    path: '/markets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKnowledgeRoute =
  AuthenticatedAdminKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDevicesRoute =
  AuthenticatedAdminDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCrmTeamIndexRoute =
  AuthenticatedCrmTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmLeadsIndexRoute =
  AuthenticatedCrmLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedAdminKnowledgeIndexRoute =
  AuthenticatedAdminKnowledgeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioVoiceAppRoute = ApiPublicTwilioVoiceAppRouteImport.update({
  id: '/api/public/twilio/voice-app',
  path: '/api/public/twilio/voice-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioSmsStatusRoute =
  ApiPublicTwilioSmsStatusRouteImport.update({
    id: '/api/public/twilio/sms-status',
    path: '/api/public/twilio/sms-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioSmsRoute = ApiPublicTwilioSmsRouteImport.update({
  id: '/api/public/twilio/sms',
  path: '/api/public/twilio/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioRecordingRoute =
  ApiPublicTwilioRecordingRouteImport.update({
    id: '/api/public/twilio/recording',
    path: '/api/public/twilio/recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioCallStatusRoute =
  ApiPublicTwilioCallStatusRouteImport.update({
    id: '/api/public/twilio/call-status',
    path: '/api/public/twilio/call-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNectarpayWebhookRoute =
  ApiPublicNectarpayWebhookRouteImport.update({
    id: '/api/public/nectarpay/webhook',
    path: '/api/public/nectarpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsIntakeRoute = ApiPublicLeadsIntakeRouteImport.update({
  id: '/api/public/leads/intake',
  path: '/api/public/leads/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEUnsubscribeRoute = ApiPublicEUnsubscribeRouteImport.update({
  id: '/api/public/e/unsubscribe',
  path: '/api/public/e/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEOpenRoute = ApiPublicEOpenRouteImport.update({
  id: '/api/public/e/open',
  path: '/api/public/e/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEClickRoute = ApiPublicEClickRouteImport.update({
  id: '/api/public/e/click',
  path: '/api/public/e/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDocsTokenRoute = ApiPublicDocsTokenRouteImport.update({
  id: '/api/public/docs/$token',
  path: '/api/public/docs/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronContingentsRoute =
  ApiPublicCronContingentsRouteImport.update({
    id: '/api/public/cron/contingents',
    path: '/api/public/cron/contingents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthWalletStatusRoute =
  ApiPublicAuthWalletStatusRouteImport.update({
    id: '/api/public/auth/wallet-status',
    path: '/api/public/auth/wallet-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthWalletExchangeRoute =
  ApiPublicAuthWalletExchangeRouteImport.update({
    id: '/api/public/auth/wallet-exchange',
    path: '/api/public/auth/wallet-exchange',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthWalletChallengeRoute =
  ApiPublicAuthWalletChallengeRouteImport.update({
    id: '/api/public/auth/wallet-challenge',
    path: '/api/public/auth/wallet-challenge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthWalletCallbackRoute =
  ApiPublicAuthWalletCallbackRouteImport.update({
    id: '/api/public/auth/wallet-callback',
    path: '/api/public/auth/wallet-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCrmTeamRepIdRoute =
  AuthenticatedCrmTeamRepIdRouteImport.update({
    id: '/team/$repId',
    path: '/team/$repId',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmLeadsIdRoute = AuthenticatedCrmLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedAdminKnowledgeTermsRoute =
  AuthenticatedAdminKnowledgeTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgePrivacyRoute =
  AuthenticatedAdminKnowledgePrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeNewRoute =
  AuthenticatedAdminKnowledgeNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeMembersHeatmapRoute =
  AuthenticatedAdminKnowledgeMembersHeatmapRouteImport.update({
    id: '/members-heatmap',
    path: '/members-heatmap',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeManifestoRoute =
  AuthenticatedAdminKnowledgeManifestoRouteImport.update({
    id: '/manifesto',
    path: '/manifesto',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeExecutiveSummaryRoute =
  AuthenticatedAdminKnowledgeExecutiveSummaryRouteImport.update({
    id: '/executive-summary',
    path: '/executive-summary',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeConvenienceDoctrineRoute =
  AuthenticatedAdminKnowledgeConvenienceDoctrineRouteImport.update({
    id: '/convenience-doctrine',
    path: '/convenience-doctrine',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeTrainingSalesRepsRoute =
  AuthenticatedAdminKnowledgeTrainingSalesRepsRouteImport.update({
    id: '/training/sales-reps',
    path: '/training/sales-reps',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute =
  AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRouteImport.update({
    id: '/training/merchant-onboarding',
    path: '/training/merchant-onboarding',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeTrainingCryptopopRoute =
  AuthenticatedAdminKnowledgeTrainingCryptopopRouteImport.update({
    id: '/training/cryptopop',
    path: '/training/cryptopop',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgePitchNewMarketsRoute =
  AuthenticatedAdminKnowledgePitchNewMarketsRouteImport.update({
    id: '/pitch/new-markets',
    path: '/pitch/new-markets',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgePitchMerchantsRoute =
  AuthenticatedAdminKnowledgePitchMerchantsRouteImport.update({
    id: '/pitch/merchants',
    path: '/pitch/merchants',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgePitchConsumersRoute =
  AuthenticatedAdminKnowledgePitchConsumersRouteImport.update({
    id: '/pitch/consumers',
    path: '/pitch/consumers',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const AuthenticatedAdminKnowledgeItemItemIdRoute =
  AuthenticatedAdminKnowledgeItemItemIdRouteImport.update({
    id: '/item/$itemId',
    path: '/item/$itemId',
    getParentRoute: () => AuthenticatedAdminKnowledgeRoute,
  } as any)
const ApiPublicDocsTokenFileIdRoute =
  ApiPublicDocsTokenFileIdRouteImport.update({
    id: '/file/$id',
    path: '/file/$id',
    getParentRoute: () => ApiPublicDocsTokenRoute,
  } as any)
const AuthenticatedAdminKnowledgeItemItemIdEditRoute =
  AuthenticatedAdminKnowledgeItemItemIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAdminKnowledgeItemItemIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeRouteWithChildren
  '/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/admin/messaging': typeof AuthenticatedAdminMessagingRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/crm/campaigns': typeof AuthenticatedCrmCampaignsRoute
  '/crm/commissions': typeof AuthenticatedCrmCommissionsRoute
  '/crm/contingents': typeof AuthenticatedCrmContingentsRoute
  '/crm/map': typeof AuthenticatedCrmMapRoute
  '/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/crm/tasks': typeof AuthenticatedCrmTasksRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/admin/knowledge/convenience-doctrine': typeof AuthenticatedAdminKnowledgeConvenienceDoctrineRoute
  '/admin/knowledge/executive-summary': typeof AuthenticatedAdminKnowledgeExecutiveSummaryRoute
  '/admin/knowledge/manifesto': typeof AuthenticatedAdminKnowledgeManifestoRoute
  '/admin/knowledge/members-heatmap': typeof AuthenticatedAdminKnowledgeMembersHeatmapRoute
  '/admin/knowledge/new': typeof AuthenticatedAdminKnowledgeNewRoute
  '/admin/knowledge/privacy': typeof AuthenticatedAdminKnowledgePrivacyRoute
  '/admin/knowledge/terms': typeof AuthenticatedAdminKnowledgeTermsRoute
  '/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/crm/team/$repId': typeof AuthenticatedCrmTeamRepIdRoute
  '/api/public/auth/wallet-callback': typeof ApiPublicAuthWalletCallbackRoute
  '/api/public/auth/wallet-challenge': typeof ApiPublicAuthWalletChallengeRoute
  '/api/public/auth/wallet-exchange': typeof ApiPublicAuthWalletExchangeRoute
  '/api/public/auth/wallet-status': typeof ApiPublicAuthWalletStatusRoute
  '/api/public/cron/contingents': typeof ApiPublicCronContingentsRoute
  '/api/public/docs/$token': typeof ApiPublicDocsTokenRouteWithChildren
  '/api/public/e/click': typeof ApiPublicEClickRoute
  '/api/public/e/open': typeof ApiPublicEOpenRoute
  '/api/public/e/unsubscribe': typeof ApiPublicEUnsubscribeRoute
  '/api/public/leads/intake': typeof ApiPublicLeadsIntakeRoute
  '/api/public/nectarpay/webhook': typeof ApiPublicNectarpayWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/twilio/call-status': typeof ApiPublicTwilioCallStatusRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/sms-status': typeof ApiPublicTwilioSmsStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/api/public/twilio/voice-app': typeof ApiPublicTwilioVoiceAppRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/knowledge/': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
  '/crm/team/': typeof AuthenticatedCrmTeamIndexRoute
  '/admin/knowledge/item/$itemId': typeof AuthenticatedAdminKnowledgeItemItemIdRouteWithChildren
  '/admin/knowledge/pitch/consumers': typeof AuthenticatedAdminKnowledgePitchConsumersRoute
  '/admin/knowledge/pitch/merchants': typeof AuthenticatedAdminKnowledgePitchMerchantsRoute
  '/admin/knowledge/pitch/new-markets': typeof AuthenticatedAdminKnowledgePitchNewMarketsRoute
  '/admin/knowledge/training/cryptopop': typeof AuthenticatedAdminKnowledgeTrainingCryptopopRoute
  '/admin/knowledge/training/merchant-onboarding': typeof AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute
  '/admin/knowledge/training/sales-reps': typeof AuthenticatedAdminKnowledgeTrainingSalesRepsRoute
  '/admin/knowledge/item/$itemId/edit': typeof AuthenticatedAdminKnowledgeItemItemIdEditRoute
  '/api/public/docs/$token/file/$id': typeof ApiPublicDocsTokenFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/admin/messaging': typeof AuthenticatedAdminMessagingRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/crm/campaigns': typeof AuthenticatedCrmCampaignsRoute
  '/crm/commissions': typeof AuthenticatedCrmCommissionsRoute
  '/crm/contingents': typeof AuthenticatedCrmContingentsRoute
  '/crm/map': typeof AuthenticatedCrmMapRoute
  '/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/crm/tasks': typeof AuthenticatedCrmTasksRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/admin/knowledge/convenience-doctrine': typeof AuthenticatedAdminKnowledgeConvenienceDoctrineRoute
  '/admin/knowledge/executive-summary': typeof AuthenticatedAdminKnowledgeExecutiveSummaryRoute
  '/admin/knowledge/manifesto': typeof AuthenticatedAdminKnowledgeManifestoRoute
  '/admin/knowledge/members-heatmap': typeof AuthenticatedAdminKnowledgeMembersHeatmapRoute
  '/admin/knowledge/new': typeof AuthenticatedAdminKnowledgeNewRoute
  '/admin/knowledge/privacy': typeof AuthenticatedAdminKnowledgePrivacyRoute
  '/admin/knowledge/terms': typeof AuthenticatedAdminKnowledgeTermsRoute
  '/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/crm/team/$repId': typeof AuthenticatedCrmTeamRepIdRoute
  '/api/public/auth/wallet-callback': typeof ApiPublicAuthWalletCallbackRoute
  '/api/public/auth/wallet-challenge': typeof ApiPublicAuthWalletChallengeRoute
  '/api/public/auth/wallet-exchange': typeof ApiPublicAuthWalletExchangeRoute
  '/api/public/auth/wallet-status': typeof ApiPublicAuthWalletStatusRoute
  '/api/public/cron/contingents': typeof ApiPublicCronContingentsRoute
  '/api/public/docs/$token': typeof ApiPublicDocsTokenRouteWithChildren
  '/api/public/e/click': typeof ApiPublicEClickRoute
  '/api/public/e/open': typeof ApiPublicEOpenRoute
  '/api/public/e/unsubscribe': typeof ApiPublicEUnsubscribeRoute
  '/api/public/leads/intake': typeof ApiPublicLeadsIntakeRoute
  '/api/public/nectarpay/webhook': typeof ApiPublicNectarpayWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/twilio/call-status': typeof ApiPublicTwilioCallStatusRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/sms-status': typeof ApiPublicTwilioSmsStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/api/public/twilio/voice-app': typeof ApiPublicTwilioVoiceAppRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/knowledge': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsIndexRoute
  '/crm/team': typeof AuthenticatedCrmTeamIndexRoute
  '/admin/knowledge/item/$itemId': typeof AuthenticatedAdminKnowledgeItemItemIdRouteWithChildren
  '/admin/knowledge/pitch/consumers': typeof AuthenticatedAdminKnowledgePitchConsumersRoute
  '/admin/knowledge/pitch/merchants': typeof AuthenticatedAdminKnowledgePitchMerchantsRoute
  '/admin/knowledge/pitch/new-markets': typeof AuthenticatedAdminKnowledgePitchNewMarketsRoute
  '/admin/knowledge/training/cryptopop': typeof AuthenticatedAdminKnowledgeTrainingCryptopopRoute
  '/admin/knowledge/training/merchant-onboarding': typeof AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute
  '/admin/knowledge/training/sales-reps': typeof AuthenticatedAdminKnowledgeTrainingSalesRepsRoute
  '/admin/knowledge/item/$itemId/edit': typeof AuthenticatedAdminKnowledgeItemItemIdEditRoute
  '/api/public/docs/$token/file/$id': typeof ApiPublicDocsTokenFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/_authenticated/admin/knowledge': typeof AuthenticatedAdminKnowledgeRouteWithChildren
  '/_authenticated/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/_authenticated/admin/messaging': typeof AuthenticatedAdminMessagingRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/crm/campaigns': typeof AuthenticatedCrmCampaignsRoute
  '/_authenticated/crm/commissions': typeof AuthenticatedCrmCommissionsRoute
  '/_authenticated/crm/contingents': typeof AuthenticatedCrmContingentsRoute
  '/_authenticated/crm/map': typeof AuthenticatedCrmMapRoute
  '/_authenticated/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/_authenticated/crm/tasks': typeof AuthenticatedCrmTasksRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/admin/knowledge/convenience-doctrine': typeof AuthenticatedAdminKnowledgeConvenienceDoctrineRoute
  '/_authenticated/admin/knowledge/executive-summary': typeof AuthenticatedAdminKnowledgeExecutiveSummaryRoute
  '/_authenticated/admin/knowledge/manifesto': typeof AuthenticatedAdminKnowledgeManifestoRoute
  '/_authenticated/admin/knowledge/members-heatmap': typeof AuthenticatedAdminKnowledgeMembersHeatmapRoute
  '/_authenticated/admin/knowledge/new': typeof AuthenticatedAdminKnowledgeNewRoute
  '/_authenticated/admin/knowledge/privacy': typeof AuthenticatedAdminKnowledgePrivacyRoute
  '/_authenticated/admin/knowledge/terms': typeof AuthenticatedAdminKnowledgeTermsRoute
  '/_authenticated/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/_authenticated/crm/team/$repId': typeof AuthenticatedCrmTeamRepIdRoute
  '/api/public/auth/wallet-callback': typeof ApiPublicAuthWalletCallbackRoute
  '/api/public/auth/wallet-challenge': typeof ApiPublicAuthWalletChallengeRoute
  '/api/public/auth/wallet-exchange': typeof ApiPublicAuthWalletExchangeRoute
  '/api/public/auth/wallet-status': typeof ApiPublicAuthWalletStatusRoute
  '/api/public/cron/contingents': typeof ApiPublicCronContingentsRoute
  '/api/public/docs/$token': typeof ApiPublicDocsTokenRouteWithChildren
  '/api/public/e/click': typeof ApiPublicEClickRoute
  '/api/public/e/open': typeof ApiPublicEOpenRoute
  '/api/public/e/unsubscribe': typeof ApiPublicEUnsubscribeRoute
  '/api/public/leads/intake': typeof ApiPublicLeadsIntakeRoute
  '/api/public/nectarpay/webhook': typeof ApiPublicNectarpayWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/twilio/call-status': typeof ApiPublicTwilioCallStatusRoute
  '/api/public/twilio/recording': typeof ApiPublicTwilioRecordingRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/sms-status': typeof ApiPublicTwilioSmsStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/api/public/twilio/voice-app': typeof ApiPublicTwilioVoiceAppRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/knowledge/': typeof AuthenticatedAdminKnowledgeIndexRoute
  '/_authenticated/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
  '/_authenticated/crm/team/': typeof AuthenticatedCrmTeamIndexRoute
  '/_authenticated/admin/knowledge/item/$itemId': typeof AuthenticatedAdminKnowledgeItemItemIdRouteWithChildren
  '/_authenticated/admin/knowledge/pitch/consumers': typeof AuthenticatedAdminKnowledgePitchConsumersRoute
  '/_authenticated/admin/knowledge/pitch/merchants': typeof AuthenticatedAdminKnowledgePitchMerchantsRoute
  '/_authenticated/admin/knowledge/pitch/new-markets': typeof AuthenticatedAdminKnowledgePitchNewMarketsRoute
  '/_authenticated/admin/knowledge/training/cryptopop': typeof AuthenticatedAdminKnowledgeTrainingCryptopopRoute
  '/_authenticated/admin/knowledge/training/merchant-onboarding': typeof AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute
  '/_authenticated/admin/knowledge/training/sales-reps': typeof AuthenticatedAdminKnowledgeTrainingSalesRepsRoute
  '/_authenticated/admin/knowledge/item/$itemId/edit': typeof AuthenticatedAdminKnowledgeItemItemIdEditRoute
  '/api/public/docs/$token/file/$id': typeof ApiPublicDocsTokenFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/set-password'
    | '/admin'
    | '/crm'
    | '/admin/commissions'
    | '/admin/devices'
    | '/admin/knowledge'
    | '/admin/markets'
    | '/admin/messaging'
    | '/admin/settings'
    | '/admin/users'
    | '/crm/campaigns'
    | '/crm/commissions'
    | '/crm/contingents'
    | '/crm/map'
    | '/crm/settings'
    | '/crm/tasks'
    | '/admin/'
    | '/crm/'
    | '/admin/knowledge/convenience-doctrine'
    | '/admin/knowledge/executive-summary'
    | '/admin/knowledge/manifesto'
    | '/admin/knowledge/members-heatmap'
    | '/admin/knowledge/new'
    | '/admin/knowledge/privacy'
    | '/admin/knowledge/terms'
    | '/crm/leads/$id'
    | '/crm/team/$repId'
    | '/api/public/auth/wallet-callback'
    | '/api/public/auth/wallet-challenge'
    | '/api/public/auth/wallet-exchange'
    | '/api/public/auth/wallet-status'
    | '/api/public/cron/contingents'
    | '/api/public/docs/$token'
    | '/api/public/e/click'
    | '/api/public/e/open'
    | '/api/public/e/unsubscribe'
    | '/api/public/leads/intake'
    | '/api/public/nectarpay/webhook'
    | '/api/public/telegram/webhook'
    | '/api/public/twilio/call-status'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/sms-status'
    | '/api/public/twilio/voice'
    | '/api/public/twilio/voice-app'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/knowledge/'
    | '/crm/leads/'
    | '/crm/team/'
    | '/admin/knowledge/item/$itemId'
    | '/admin/knowledge/pitch/consumers'
    | '/admin/knowledge/pitch/merchants'
    | '/admin/knowledge/pitch/new-markets'
    | '/admin/knowledge/training/cryptopop'
    | '/admin/knowledge/training/merchant-onboarding'
    | '/admin/knowledge/training/sales-reps'
    | '/admin/knowledge/item/$itemId/edit'
    | '/api/public/docs/$token/file/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/set-password'
    | '/admin/commissions'
    | '/admin/devices'
    | '/admin/markets'
    | '/admin/messaging'
    | '/admin/settings'
    | '/admin/users'
    | '/crm/campaigns'
    | '/crm/commissions'
    | '/crm/contingents'
    | '/crm/map'
    | '/crm/settings'
    | '/crm/tasks'
    | '/admin'
    | '/crm'
    | '/admin/knowledge/convenience-doctrine'
    | '/admin/knowledge/executive-summary'
    | '/admin/knowledge/manifesto'
    | '/admin/knowledge/members-heatmap'
    | '/admin/knowledge/new'
    | '/admin/knowledge/privacy'
    | '/admin/knowledge/terms'
    | '/crm/leads/$id'
    | '/crm/team/$repId'
    | '/api/public/auth/wallet-callback'
    | '/api/public/auth/wallet-challenge'
    | '/api/public/auth/wallet-exchange'
    | '/api/public/auth/wallet-status'
    | '/api/public/cron/contingents'
    | '/api/public/docs/$token'
    | '/api/public/e/click'
    | '/api/public/e/open'
    | '/api/public/e/unsubscribe'
    | '/api/public/leads/intake'
    | '/api/public/nectarpay/webhook'
    | '/api/public/telegram/webhook'
    | '/api/public/twilio/call-status'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/sms-status'
    | '/api/public/twilio/voice'
    | '/api/public/twilio/voice-app'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/knowledge'
    | '/crm/leads'
    | '/crm/team'
    | '/admin/knowledge/item/$itemId'
    | '/admin/knowledge/pitch/consumers'
    | '/admin/knowledge/pitch/merchants'
    | '/admin/knowledge/pitch/new-markets'
    | '/admin/knowledge/training/cryptopop'
    | '/admin/knowledge/training/merchant-onboarding'
    | '/admin/knowledge/training/sales-reps'
    | '/admin/knowledge/item/$itemId/edit'
    | '/api/public/docs/$token/file/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/set-password'
    | '/_authenticated/admin'
    | '/_authenticated/crm'
    | '/_authenticated/admin/commissions'
    | '/_authenticated/admin/devices'
    | '/_authenticated/admin/knowledge'
    | '/_authenticated/admin/markets'
    | '/_authenticated/admin/messaging'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/crm/campaigns'
    | '/_authenticated/crm/commissions'
    | '/_authenticated/crm/contingents'
    | '/_authenticated/crm/map'
    | '/_authenticated/crm/settings'
    | '/_authenticated/crm/tasks'
    | '/_authenticated/admin/'
    | '/_authenticated/crm/'
    | '/_authenticated/admin/knowledge/convenience-doctrine'
    | '/_authenticated/admin/knowledge/executive-summary'
    | '/_authenticated/admin/knowledge/manifesto'
    | '/_authenticated/admin/knowledge/members-heatmap'
    | '/_authenticated/admin/knowledge/new'
    | '/_authenticated/admin/knowledge/privacy'
    | '/_authenticated/admin/knowledge/terms'
    | '/_authenticated/crm/leads/$id'
    | '/_authenticated/crm/team/$repId'
    | '/api/public/auth/wallet-callback'
    | '/api/public/auth/wallet-challenge'
    | '/api/public/auth/wallet-exchange'
    | '/api/public/auth/wallet-status'
    | '/api/public/cron/contingents'
    | '/api/public/docs/$token'
    | '/api/public/e/click'
    | '/api/public/e/open'
    | '/api/public/e/unsubscribe'
    | '/api/public/leads/intake'
    | '/api/public/nectarpay/webhook'
    | '/api/public/telegram/webhook'
    | '/api/public/twilio/call-status'
    | '/api/public/twilio/recording'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/sms-status'
    | '/api/public/twilio/voice'
    | '/api/public/twilio/voice-app'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/knowledge/'
    | '/_authenticated/crm/leads/'
    | '/_authenticated/crm/team/'
    | '/_authenticated/admin/knowledge/item/$itemId'
    | '/_authenticated/admin/knowledge/pitch/consumers'
    | '/_authenticated/admin/knowledge/pitch/merchants'
    | '/_authenticated/admin/knowledge/pitch/new-markets'
    | '/_authenticated/admin/knowledge/training/cryptopop'
    | '/_authenticated/admin/knowledge/training/merchant-onboarding'
    | '/_authenticated/admin/knowledge/training/sales-reps'
    | '/_authenticated/admin/knowledge/item/$itemId/edit'
    | '/api/public/docs/$token/file/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetPasswordRoute: typeof SetPasswordRoute
  ApiPublicAuthWalletCallbackRoute: typeof ApiPublicAuthWalletCallbackRoute
  ApiPublicAuthWalletChallengeRoute: typeof ApiPublicAuthWalletChallengeRoute
  ApiPublicAuthWalletExchangeRoute: typeof ApiPublicAuthWalletExchangeRoute
  ApiPublicAuthWalletStatusRoute: typeof ApiPublicAuthWalletStatusRoute
  ApiPublicCronContingentsRoute: typeof ApiPublicCronContingentsRoute
  ApiPublicDocsTokenRoute: typeof ApiPublicDocsTokenRouteWithChildren
  ApiPublicEClickRoute: typeof ApiPublicEClickRoute
  ApiPublicEOpenRoute: typeof ApiPublicEOpenRoute
  ApiPublicEUnsubscribeRoute: typeof ApiPublicEUnsubscribeRoute
  ApiPublicLeadsIntakeRoute: typeof ApiPublicLeadsIntakeRoute
  ApiPublicNectarpayWebhookRoute: typeof ApiPublicNectarpayWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicTwilioCallStatusRoute: typeof ApiPublicTwilioCallStatusRoute
  ApiPublicTwilioRecordingRoute: typeof ApiPublicTwilioRecordingRoute
  ApiPublicTwilioSmsRoute: typeof ApiPublicTwilioSmsRoute
  ApiPublicTwilioSmsStatusRoute: typeof ApiPublicTwilioSmsStatusRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
  ApiPublicTwilioVoiceAppRoute: typeof ApiPublicTwilioVoiceAppRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/crm/tasks': {
      id: '/_authenticated/crm/tasks'
      path: '/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof AuthenticatedCrmTasksRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/settings': {
      id: '/_authenticated/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof AuthenticatedCrmSettingsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/map': {
      id: '/_authenticated/crm/map'
      path: '/map'
      fullPath: '/crm/map'
      preLoaderRoute: typeof AuthenticatedCrmMapRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/contingents': {
      id: '/_authenticated/crm/contingents'
      path: '/contingents'
      fullPath: '/crm/contingents'
      preLoaderRoute: typeof AuthenticatedCrmContingentsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/commissions': {
      id: '/_authenticated/crm/commissions'
      path: '/commissions'
      fullPath: '/crm/commissions'
      preLoaderRoute: typeof AuthenticatedCrmCommissionsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/campaigns': {
      id: '/_authenticated/crm/campaigns'
      path: '/campaigns'
      fullPath: '/crm/campaigns'
      preLoaderRoute: typeof AuthenticatedCrmCampaignsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messaging': {
      id: '/_authenticated/admin/messaging'
      path: '/messaging'
      fullPath: '/admin/messaging'
      preLoaderRoute: typeof AuthenticatedAdminMessagingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/markets': {
      id: '/_authenticated/admin/markets'
      path: '/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AuthenticatedAdminMarketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/knowledge': {
      id: '/_authenticated/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/devices': {
      id: '/_authenticated/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AuthenticatedAdminDevicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/commissions': {
      id: '/_authenticated/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/crm/team/': {
      id: '/_authenticated/crm/team/'
      path: '/team'
      fullPath: '/crm/team/'
      preLoaderRoute: typeof AuthenticatedCrmTeamIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/leads/': {
      id: '/_authenticated/crm/leads/'
      path: '/leads'
      fullPath: '/crm/leads/'
      preLoaderRoute: typeof AuthenticatedCrmLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/admin/knowledge/': {
      id: '/_authenticated/admin/knowledge/'
      path: '/'
      fullPath: '/admin/knowledge/'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice-app': {
      id: '/api/public/twilio/voice-app'
      path: '/api/public/twilio/voice-app'
      fullPath: '/api/public/twilio/voice-app'
      preLoaderRoute: typeof ApiPublicTwilioVoiceAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms-status': {
      id: '/api/public/twilio/sms-status'
      path: '/api/public/twilio/sms-status'
      fullPath: '/api/public/twilio/sms-status'
      preLoaderRoute: typeof ApiPublicTwilioSmsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms': {
      id: '/api/public/twilio/sms'
      path: '/api/public/twilio/sms'
      fullPath: '/api/public/twilio/sms'
      preLoaderRoute: typeof ApiPublicTwilioSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/recording': {
      id: '/api/public/twilio/recording'
      path: '/api/public/twilio/recording'
      fullPath: '/api/public/twilio/recording'
      preLoaderRoute: typeof ApiPublicTwilioRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/call-status': {
      id: '/api/public/twilio/call-status'
      path: '/api/public/twilio/call-status'
      fullPath: '/api/public/twilio/call-status'
      preLoaderRoute: typeof ApiPublicTwilioCallStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nectarpay/webhook': {
      id: '/api/public/nectarpay/webhook'
      path: '/api/public/nectarpay/webhook'
      fullPath: '/api/public/nectarpay/webhook'
      preLoaderRoute: typeof ApiPublicNectarpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/intake': {
      id: '/api/public/leads/intake'
      path: '/api/public/leads/intake'
      fullPath: '/api/public/leads/intake'
      preLoaderRoute: typeof ApiPublicLeadsIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/e/unsubscribe': {
      id: '/api/public/e/unsubscribe'
      path: '/api/public/e/unsubscribe'
      fullPath: '/api/public/e/unsubscribe'
      preLoaderRoute: typeof ApiPublicEUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/e/open': {
      id: '/api/public/e/open'
      path: '/api/public/e/open'
      fullPath: '/api/public/e/open'
      preLoaderRoute: typeof ApiPublicEOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/e/click': {
      id: '/api/public/e/click'
      path: '/api/public/e/click'
      fullPath: '/api/public/e/click'
      preLoaderRoute: typeof ApiPublicEClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/docs/$token': {
      id: '/api/public/docs/$token'
      path: '/api/public/docs/$token'
      fullPath: '/api/public/docs/$token'
      preLoaderRoute: typeof ApiPublicDocsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/contingents': {
      id: '/api/public/cron/contingents'
      path: '/api/public/cron/contingents'
      fullPath: '/api/public/cron/contingents'
      preLoaderRoute: typeof ApiPublicCronContingentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/wallet-status': {
      id: '/api/public/auth/wallet-status'
      path: '/api/public/auth/wallet-status'
      fullPath: '/api/public/auth/wallet-status'
      preLoaderRoute: typeof ApiPublicAuthWalletStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/wallet-exchange': {
      id: '/api/public/auth/wallet-exchange'
      path: '/api/public/auth/wallet-exchange'
      fullPath: '/api/public/auth/wallet-exchange'
      preLoaderRoute: typeof ApiPublicAuthWalletExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/wallet-challenge': {
      id: '/api/public/auth/wallet-challenge'
      path: '/api/public/auth/wallet-challenge'
      fullPath: '/api/public/auth/wallet-challenge'
      preLoaderRoute: typeof ApiPublicAuthWalletChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/wallet-callback': {
      id: '/api/public/auth/wallet-callback'
      path: '/api/public/auth/wallet-callback'
      fullPath: '/api/public/auth/wallet-callback'
      preLoaderRoute: typeof ApiPublicAuthWalletCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm/team/$repId': {
      id: '/_authenticated/crm/team/$repId'
      path: '/team/$repId'
      fullPath: '/crm/team/$repId'
      preLoaderRoute: typeof AuthenticatedCrmTeamRepIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/leads/$id': {
      id: '/_authenticated/crm/leads/$id'
      path: '/leads/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof AuthenticatedCrmLeadsIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/admin/knowledge/terms': {
      id: '/_authenticated/admin/knowledge/terms'
      path: '/terms'
      fullPath: '/admin/knowledge/terms'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeTermsRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/privacy': {
      id: '/_authenticated/admin/knowledge/privacy'
      path: '/privacy'
      fullPath: '/admin/knowledge/privacy'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgePrivacyRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/new': {
      id: '/_authenticated/admin/knowledge/new'
      path: '/new'
      fullPath: '/admin/knowledge/new'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeNewRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/members-heatmap': {
      id: '/_authenticated/admin/knowledge/members-heatmap'
      path: '/members-heatmap'
      fullPath: '/admin/knowledge/members-heatmap'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeMembersHeatmapRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/manifesto': {
      id: '/_authenticated/admin/knowledge/manifesto'
      path: '/manifesto'
      fullPath: '/admin/knowledge/manifesto'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeManifestoRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/executive-summary': {
      id: '/_authenticated/admin/knowledge/executive-summary'
      path: '/executive-summary'
      fullPath: '/admin/knowledge/executive-summary'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeExecutiveSummaryRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/convenience-doctrine': {
      id: '/_authenticated/admin/knowledge/convenience-doctrine'
      path: '/convenience-doctrine'
      fullPath: '/admin/knowledge/convenience-doctrine'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeConvenienceDoctrineRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/training/sales-reps': {
      id: '/_authenticated/admin/knowledge/training/sales-reps'
      path: '/training/sales-reps'
      fullPath: '/admin/knowledge/training/sales-reps'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeTrainingSalesRepsRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/training/merchant-onboarding': {
      id: '/_authenticated/admin/knowledge/training/merchant-onboarding'
      path: '/training/merchant-onboarding'
      fullPath: '/admin/knowledge/training/merchant-onboarding'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/training/cryptopop': {
      id: '/_authenticated/admin/knowledge/training/cryptopop'
      path: '/training/cryptopop'
      fullPath: '/admin/knowledge/training/cryptopop'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeTrainingCryptopopRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/pitch/new-markets': {
      id: '/_authenticated/admin/knowledge/pitch/new-markets'
      path: '/pitch/new-markets'
      fullPath: '/admin/knowledge/pitch/new-markets'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgePitchNewMarketsRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/pitch/merchants': {
      id: '/_authenticated/admin/knowledge/pitch/merchants'
      path: '/pitch/merchants'
      fullPath: '/admin/knowledge/pitch/merchants'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgePitchMerchantsRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/pitch/consumers': {
      id: '/_authenticated/admin/knowledge/pitch/consumers'
      path: '/pitch/consumers'
      fullPath: '/admin/knowledge/pitch/consumers'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgePitchConsumersRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/_authenticated/admin/knowledge/item/$itemId': {
      id: '/_authenticated/admin/knowledge/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/admin/knowledge/item/$itemId'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeItemItemIdRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeRoute
    }
    '/api/public/docs/$token/file/$id': {
      id: '/api/public/docs/$token/file/$id'
      path: '/file/$id'
      fullPath: '/api/public/docs/$token/file/$id'
      preLoaderRoute: typeof ApiPublicDocsTokenFileIdRouteImport
      parentRoute: typeof ApiPublicDocsTokenRoute
    }
    '/_authenticated/admin/knowledge/item/$itemId/edit': {
      id: '/_authenticated/admin/knowledge/item/$itemId/edit'
      path: '/edit'
      fullPath: '/admin/knowledge/item/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeItemItemIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminKnowledgeItemItemIdRoute
    }
  }
}

interface AuthenticatedAdminKnowledgeItemItemIdRouteChildren {
  AuthenticatedAdminKnowledgeItemItemIdEditRoute: typeof AuthenticatedAdminKnowledgeItemItemIdEditRoute
}

const AuthenticatedAdminKnowledgeItemItemIdRouteChildren: AuthenticatedAdminKnowledgeItemItemIdRouteChildren =
  {
    AuthenticatedAdminKnowledgeItemItemIdEditRoute:
      AuthenticatedAdminKnowledgeItemItemIdEditRoute,
  }

const AuthenticatedAdminKnowledgeItemItemIdRouteWithChildren =
  AuthenticatedAdminKnowledgeItemItemIdRoute._addFileChildren(
    AuthenticatedAdminKnowledgeItemItemIdRouteChildren,
  )

interface AuthenticatedAdminKnowledgeRouteChildren {
  AuthenticatedAdminKnowledgeConvenienceDoctrineRoute: typeof AuthenticatedAdminKnowledgeConvenienceDoctrineRoute
  AuthenticatedAdminKnowledgeExecutiveSummaryRoute: typeof AuthenticatedAdminKnowledgeExecutiveSummaryRoute
  AuthenticatedAdminKnowledgeManifestoRoute: typeof AuthenticatedAdminKnowledgeManifestoRoute
  AuthenticatedAdminKnowledgeMembersHeatmapRoute: typeof AuthenticatedAdminKnowledgeMembersHeatmapRoute
  AuthenticatedAdminKnowledgeNewRoute: typeof AuthenticatedAdminKnowledgeNewRoute
  AuthenticatedAdminKnowledgePrivacyRoute: typeof AuthenticatedAdminKnowledgePrivacyRoute
  AuthenticatedAdminKnowledgeTermsRoute: typeof AuthenticatedAdminKnowledgeTermsRoute
  AuthenticatedAdminKnowledgeIndexRoute: typeof AuthenticatedAdminKnowledgeIndexRoute
  AuthenticatedAdminKnowledgeItemItemIdRoute: typeof AuthenticatedAdminKnowledgeItemItemIdRouteWithChildren
  AuthenticatedAdminKnowledgePitchConsumersRoute: typeof AuthenticatedAdminKnowledgePitchConsumersRoute
  AuthenticatedAdminKnowledgePitchMerchantsRoute: typeof AuthenticatedAdminKnowledgePitchMerchantsRoute
  AuthenticatedAdminKnowledgePitchNewMarketsRoute: typeof AuthenticatedAdminKnowledgePitchNewMarketsRoute
  AuthenticatedAdminKnowledgeTrainingCryptopopRoute: typeof AuthenticatedAdminKnowledgeTrainingCryptopopRoute
  AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute: typeof AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute
  AuthenticatedAdminKnowledgeTrainingSalesRepsRoute: typeof AuthenticatedAdminKnowledgeTrainingSalesRepsRoute
}

const AuthenticatedAdminKnowledgeRouteChildren: AuthenticatedAdminKnowledgeRouteChildren =
  {
    AuthenticatedAdminKnowledgeConvenienceDoctrineRoute:
      AuthenticatedAdminKnowledgeConvenienceDoctrineRoute,
    AuthenticatedAdminKnowledgeExecutiveSummaryRoute:
      AuthenticatedAdminKnowledgeExecutiveSummaryRoute,
    AuthenticatedAdminKnowledgeManifestoRoute:
      AuthenticatedAdminKnowledgeManifestoRoute,
    AuthenticatedAdminKnowledgeMembersHeatmapRoute:
      AuthenticatedAdminKnowledgeMembersHeatmapRoute,
    AuthenticatedAdminKnowledgeNewRoute: AuthenticatedAdminKnowledgeNewRoute,
    AuthenticatedAdminKnowledgePrivacyRoute:
      AuthenticatedAdminKnowledgePrivacyRoute,
    AuthenticatedAdminKnowledgeTermsRoute:
      AuthenticatedAdminKnowledgeTermsRoute,
    AuthenticatedAdminKnowledgeIndexRoute:
      AuthenticatedAdminKnowledgeIndexRoute,
    AuthenticatedAdminKnowledgeItemItemIdRoute:
      AuthenticatedAdminKnowledgeItemItemIdRouteWithChildren,
    AuthenticatedAdminKnowledgePitchConsumersRoute:
      AuthenticatedAdminKnowledgePitchConsumersRoute,
    AuthenticatedAdminKnowledgePitchMerchantsRoute:
      AuthenticatedAdminKnowledgePitchMerchantsRoute,
    AuthenticatedAdminKnowledgePitchNewMarketsRoute:
      AuthenticatedAdminKnowledgePitchNewMarketsRoute,
    AuthenticatedAdminKnowledgeTrainingCryptopopRoute:
      AuthenticatedAdminKnowledgeTrainingCryptopopRoute,
    AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute:
      AuthenticatedAdminKnowledgeTrainingMerchantOnboardingRoute,
    AuthenticatedAdminKnowledgeTrainingSalesRepsRoute:
      AuthenticatedAdminKnowledgeTrainingSalesRepsRoute,
  }

const AuthenticatedAdminKnowledgeRouteWithChildren =
  AuthenticatedAdminKnowledgeRoute._addFileChildren(
    AuthenticatedAdminKnowledgeRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminDevicesRoute: typeof AuthenticatedAdminDevicesRoute
  AuthenticatedAdminKnowledgeRoute: typeof AuthenticatedAdminKnowledgeRouteWithChildren
  AuthenticatedAdminMarketsRoute: typeof AuthenticatedAdminMarketsRoute
  AuthenticatedAdminMessagingRoute: typeof AuthenticatedAdminMessagingRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
  AuthenticatedAdminDevicesRoute: AuthenticatedAdminDevicesRoute,
  AuthenticatedAdminKnowledgeRoute:
    AuthenticatedAdminKnowledgeRouteWithChildren,
  AuthenticatedAdminMarketsRoute: AuthenticatedAdminMarketsRoute,
  AuthenticatedAdminMessagingRoute: AuthenticatedAdminMessagingRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmCampaignsRoute: typeof AuthenticatedCrmCampaignsRoute
  AuthenticatedCrmCommissionsRoute: typeof AuthenticatedCrmCommissionsRoute
  AuthenticatedCrmContingentsRoute: typeof AuthenticatedCrmContingentsRoute
  AuthenticatedCrmMapRoute: typeof AuthenticatedCrmMapRoute
  AuthenticatedCrmSettingsRoute: typeof AuthenticatedCrmSettingsRoute
  AuthenticatedCrmTasksRoute: typeof AuthenticatedCrmTasksRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedCrmLeadsIdRoute: typeof AuthenticatedCrmLeadsIdRoute
  AuthenticatedCrmTeamRepIdRoute: typeof AuthenticatedCrmTeamRepIdRoute
  AuthenticatedCrmLeadsIndexRoute: typeof AuthenticatedCrmLeadsIndexRoute
  AuthenticatedCrmTeamIndexRoute: typeof AuthenticatedCrmTeamIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmCampaignsRoute: AuthenticatedCrmCampaignsRoute,
  AuthenticatedCrmCommissionsRoute: AuthenticatedCrmCommissionsRoute,
  AuthenticatedCrmContingentsRoute: AuthenticatedCrmContingentsRoute,
  AuthenticatedCrmMapRoute: AuthenticatedCrmMapRoute,
  AuthenticatedCrmSettingsRoute: AuthenticatedCrmSettingsRoute,
  AuthenticatedCrmTasksRoute: AuthenticatedCrmTasksRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedCrmLeadsIdRoute: AuthenticatedCrmLeadsIdRoute,
  AuthenticatedCrmTeamRepIdRoute: AuthenticatedCrmTeamRepIdRoute,
  AuthenticatedCrmLeadsIndexRoute: AuthenticatedCrmLeadsIndexRoute,
  AuthenticatedCrmTeamIndexRoute: AuthenticatedCrmTeamIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicDocsTokenRouteChildren {
  ApiPublicDocsTokenFileIdRoute: typeof ApiPublicDocsTokenFileIdRoute
}

const ApiPublicDocsTokenRouteChildren: ApiPublicDocsTokenRouteChildren = {
  ApiPublicDocsTokenFileIdRoute: ApiPublicDocsTokenFileIdRoute,
}

const ApiPublicDocsTokenRouteWithChildren =
  ApiPublicDocsTokenRoute._addFileChildren(ApiPublicDocsTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SetPasswordRoute: SetPasswordRoute,
  ApiPublicAuthWalletCallbackRoute: ApiPublicAuthWalletCallbackRoute,
  ApiPublicAuthWalletChallengeRoute: ApiPublicAuthWalletChallengeRoute,
  ApiPublicAuthWalletExchangeRoute: ApiPublicAuthWalletExchangeRoute,
  ApiPublicAuthWalletStatusRoute: ApiPublicAuthWalletStatusRoute,
  ApiPublicCronContingentsRoute: ApiPublicCronContingentsRoute,
  ApiPublicDocsTokenRoute: ApiPublicDocsTokenRouteWithChildren,
  ApiPublicEClickRoute: ApiPublicEClickRoute,
  ApiPublicEOpenRoute: ApiPublicEOpenRoute,
  ApiPublicEUnsubscribeRoute: ApiPublicEUnsubscribeRoute,
  ApiPublicLeadsIntakeRoute: ApiPublicLeadsIntakeRoute,
  ApiPublicNectarpayWebhookRoute: ApiPublicNectarpayWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicTwilioCallStatusRoute: ApiPublicTwilioCallStatusRoute,
  ApiPublicTwilioRecordingRoute: ApiPublicTwilioRecordingRoute,
  ApiPublicTwilioSmsRoute: ApiPublicTwilioSmsRoute,
  ApiPublicTwilioSmsStatusRoute: ApiPublicTwilioSmsStatusRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
  ApiPublicTwilioVoiceAppRoute: ApiPublicTwilioVoiceAppRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
